name: geese_relief
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  path_provider:
  flushbar:
  material_design_icons_flutter:
  shimmer:
  intl:
  connectivity:
  image_picker:
  async:
  dotted_border:
  flappy_search_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Monserrat
      fonts:
        - asset: fonts/font_bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/font_regular.ttf
          weight: 700